apiVersion: v1
kind: Service
metadata:
  name: kuber-service
spec:
  selector:
    app: https-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: https-server-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: https-server
  template:
    metadata:
      labels:
        app: https-server
    spec:
      containers:
        - name: https-server
          image: nginx:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "128Mi"
              cpu: "500m"
            limits:
              memory: "256Mi"
              cpu: "1000m"
